# --- Sleepy Configuration ---
# This configuration file is compatible with versions 4.x or higher.


# -- [Secrets] --

# The Discord token to authenticate with. (required)
# Get one from: https://discord.com/developers
discord_auth_token: your_discord_bot_token_here

# The bot's Discord webhook for statistics and logging. (required)
# Get one from Edit Channel > Integrations > Webhooks
# Example URL: https://discord.com/api/webhooks/<id>/<token>
discord_webhook_url: your_discord_webhook_url_here

# The API key to interact with Google's APIs.
# Get one from: https://console.cloud.google.com/apis
google_api_key: your_google_api_key_here

# The custom search engine ID for use with Google Search.
# Get one from: https://cse.google.com
google_search_engine_id: your_google_search_engine_id_here

# The API key to interact with WeatherAPI.
# Get one from: https://weatherapi.com
weatherapi_api_key: your_weatherapi_api_key_here

# The API key to interact with Steam's APIs.
# Get one from: https://steamcommunity.com/dev/apikey
steam_api_key: your_steam_api_key_here


# -- [General Config] --

# The bot's description.
description: |-
  A Discord bot for those who like to sleep.
  This bot is running an instance of Sleepy (<https://github.com/HitchedSyringe/Sleepy>).

# The bot's command prefixes.
# Users will have to prefix commands with these.
prefixes:
  - $*

# Whether or not the bot's mention should be a valid prefix.
# If ``prefixes`` is empty, then the bot's mention will be
# used, regardless of this setting.
mentionable: true

# Whether or not the cog names are case-insensitive.
# This is useful for making help more user-friendly.
# This setting cannot be changed once initialised.
case_insensitive_cogs: false

# The user IDs that own the bot.
# These users can use every command, as well as bypass cooldowns
# and checks. **This is a dangerous permission to grant.**
# If this is empty, then the owner IDs will be queried on login.
# This is ignored if either the `owner_id` or `owner_ids` kwargs
# were passed into the Sleepy bot constructor, or the respective
# attributes were set prior to login.
owner_ids: []

# Whether or not to query the owner IDs from the bot's application
# info on startup, regardless of whether ``owner_ids`` is empty.
# If ``owner_ids`` is not empty, then the queried owner IDs will
# be merged with the configured owner IDs.
# This is ignored if either the `owner_id` or `owner_ids` kwargs
# were passed into the Sleepy bot constructor, or the respective
# attributes were set prior to logging in.
# ~~ Added in version 3.3.
force_querying_owner_ids: false

# The extensions to load.
# Folders and files should be separated via periods (.).
# Although forward (/) and back (\) slashes work as well
# due to an implementation detail, periods are preferred.
# DO NOT include the '.py' file extension in the entry.
# -> Example: my.important.extension
# This also uses wildcard syntax to specify loading all
# extensions in the given directory.
# -> Example: my.core.*
# Additionally, this also uses `braceexpand` syntax for
# granularity in selecting extensions to load. For more
# information, refer to the `braceexpand` documentation.
# -> Example 1: my.extensions.{this,that}
# -> Example 2: my.extensions.{extension{1..5}}
# -> ...among other things.
# NOTE: It is recommended that extension names refrain
# from using any aforementioned separator characters to
# avoid ambiguity when loading. For instance, the name
# `my.period.separated` could either mean the extension
# `my/period.separated` or the extension `separated` in
# directory `my/period`).
# ~~ Changed in version 4.0:
#    Bring extension syntax to parity with `jishaku`'s.
extensions_list:
  - sleepy.ext.jishaku
  - sleepy.ext.meta
  - sleepy.ext.statistics
